Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SkyBlueBlue.Models;
using Microsoft.AspNetCore.Http;

namespace SkyBlueBlue.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public AuthController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginModel)
        {
            if(!ModelState.IsValid)
            {
                
                return View(loginModel);
            }
            var user=await userManager.FindByNameAsync(loginModel.userName);
            if(user!=null)
            {
                var result = await signInManager.PasswordSignInAsync(user,loginModel.password,false,false);
                if(result.Succeeded)
                {
                    HttpContext.Session.SetString("Avatar", user.avatar);
                    return RedirectToAction("Index","Home",new {user.avatar});
                }
            }
            ModelState.AddModelError("","账号/密码不正确");
            return View(loginModel);
        }
        [HttpGet]
        public IActionResult Register()
        {
            return  View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel registerModel)
        {
           if(ModelState.IsValid)
            {
                var user =new ApplicationUser{
                    UserName=registerModel.userName,
                    avatar=registerModel.avatar
                };
                var result=await userManager.CreateAsync(user,registerModel.password);
                var result2=await userManager.AddToRoleAsync(user,"Student");
                if(result.Succeeded&&result2.Succeeded)
                {
                    // HttpContext.Session.SetString("Avatar", user.avatar);
                    // return RedirectToAction("Index","Home",new {user.avatar});
                    return RedirectToAction("Login");
                }
            }
            return View(registerModel);
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

Controllers/MyController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SkyBlueBlue.Models;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using SkyBlueBlue.Services;

namespace SkyBlueBlue.Controllers
{
    [Authorize]
    public class MyController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly SuccessManager successManager;

        public MyController(
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager,
            SuccessManager successManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.successManager = successManager;
        }
        public async Task<IActionResult> Index()
        {
            var a = User.Identity.Name;
            var my = await userManager.FindByNameAsync(User.Identity.Name);
            return View(
                new MyInfoModel
                {
                    id = my.Id,
                    userName = my.UserName,
                    roles = await userManager.GetRolesAsync(my),
                    avatar = my.avatar,
                    email = my.Email
                }
            );
        }

        public async Task<IActionResult> CheckHistory()
        {
            var successList= await successManager.FindSuccessByUserNameAsync(User.Identity.Name);
            ViewBag.SuccessList = successList;
            return View();
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            var my = await userManager.FindByNameAsync(HttpContext.User.Identity.Name);
            if (my != null)
            {
                var result =  await userManager.ChangePasswordAsync(my,model.oldPassword,model.newPassword);
                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty,"原密码错误");
                return View(model);
            }
            
            return View(model);
        }
    }
}

Controllers/RoleController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SkyBlueBlue.Models;

namespace SkyBlueBlue.Controllers
{
    // [Authorize(Roles = "Administrators")]
    // [Authorize(Policy="仅限管理员")]
    // [Authorize]
    [Authorize(Roles = "Administrators")]
    public class RoleController:Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public RoleController(
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        [HttpGet]

        public async Task<IActionResult> Index()
        {
            var roles = await roleManager.Roles.ToListAsync();
            return View(roles);
        }

        public IActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(RoleAddViewModel roleAddViewModel)
        {
            if(!ModelState.IsValid)
            {
                return View(roleAddViewModel);
            }
            var role = new IdentityRole
            {
                Name = roleAddViewModel.RoleName
            };
            var result = await roleManager.CreateAsync(role);
            if(result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach(var item in result.Errors)
            {
                ModelState.AddModelError(string.Empty,item.Description);
            }
            return View(roleAddViewModel);
        }

        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if(role == null)
            {
                return RedirectToAction("Index");
            }
            var roleEditViewModel = new RoleEditViewModel
            {
                Id = id,
                RoleName = role.Name,
                Users = new List<string>()
            };

            var users = await userManager.Users.ToListAsync();
            foreach(var item in users)
            {
                if(await userManager.IsInRoleAsync(item, role.Name))
                {
                    roleEditViewModel.Users.Add(item.UserName);
                }
            }
            return View(roleEditViewModel);

        }


        [HttpPost]
        public async Task<IActionResult> EditRole (RoleEditViewModel roleEditViewModel)
        {
            var role =await roleManager.FindByIdAsync(roleEditViewModel.Id);
            if(role != null)
            {
                role.Name = roleEditViewModel.RoleName;
                var result = await roleManager.UpdateAsync(role);
                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty,"更新角色时出错");
                return View(roleEditViewModel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var role =await roleManager.FindByIdAsync(id);
            if(role != null)
            {
                var result = await roleManager.DeleteAsync(role);
                if(result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                    ModelState.AddModelError(string.Empty,"删除用户时发生错误");
            }
            else
            {
                ModelState.AddModelError(string.Empty,"用户找不到");
            }
            return View("Index",await roleManager.Roles.ToArrayAsync());
        }
        [HttpGet]
        public async Task<IActionResult> AddUserToRole(string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                return RedirectToAction("Index");
            }

            var vm = new UserRoleViewModel
            {
                RoleId = role.Id
            };

            var users = await userManager.Users.ToListAsync();

            foreach (var user in users)
            {
                if (!await userManager.IsInRoleAsync(user, role.Name))
                {
                    vm.Users.Add(user);
                }
            }

            return View(vm);

        }
        [HttpPost]
        public async Task<IActionResult> AddUserToRole(UserRoleViewModel userRoleViewModel)
        {
            var user = await userManager.FindByIdAsync(userRoleViewModel.UserId);
            var role = await roleManager.FindByIdAsync(userRoleViewModel.RoleId);

            if(user != null && role != null)
            {
                var result = await userManager.AddToRoleAsync(user,role.Name);
                if(result.Succeeded)
                {
                    return RedirectToAction("EditRole",new{id=role.Id});
                }

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty,item.Description);
                }
                return View(userRoleViewModel);
            }
            ModelState.AddModelError(string.Empty,"用户或角色未找到");
            return View(userRoleViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> RemoveUserToRole(string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                return RedirectToAction("Index");
            }

            var vm = new UserRoleViewModel
            {
                RoleId = role.Id
            };

            var users = await userManager.Users.ToListAsync();

            foreach (var user in users)
            {
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    vm.Users.Add(user);
                }
            }
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveUserToRole(UserRoleViewModel userRoleViewModel)
        {
            var user = await userManager.FindByIdAsync(userRoleViewModel.UserId);
            var role = await roleManager.FindByIdAsync(userRoleViewModel.RoleId);

            if(user != null && role != null)
            {
                
                var result = await userManager.RemoveFromRoleAsync(user,role.Name);
                if(result.Succeeded)
                {
                    return RedirectToAction("EditRole",new{id=role.Id});
                }

                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(string.Empty,item.Description);
                }
                return View(userRoleViewModel);
            }
            ModelState.AddModelError(string.Empty,"用户或角色未找到");
            return View(userRoleViewModel);
        }

        [AcceptVerbs("Get","Post")]
        public async Task<IActionResult> CheckRoleExist([Bind("RoleName")]string RoleName)
        {
            var role = await roleManager.FindByNameAsync(RoleName);
            if(role != null)
            {
                return Json("角色已经存在了");
            }
            return Json(true);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SkyBlueBlue</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="height:100%">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="padding:0;">
                    <div style="background:url(/image/logo.png);background-repeat:round;height:50px;width:120px"></div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1" style="position: relative;">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">主页</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Test">考试</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Topic" asp-action="Index">题库</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paper" asp-action="Index">试卷</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                管理
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">用户</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">角色</a>
                            </div>
                        </li>
                        @if(SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item dropdown" style="position: absolute;right:0">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    欢迎!  @Context.Session.GetString("Avatar")
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="My" asp-action="Index">设置</a>
                                    <form asp-controller="Auth" asp-action="Logout" method="post" id="logoutForm">
                                        <a class="nav-link" style="color:red"  href="javascript:document.getElementById('logoutForm').submit()">退出</a> 
                                    </form>
                                </div>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="height:100%">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Kalearn
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>