Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkyBlueBlue.Models;
using SkyBlueBlue.Services;

namespace SkyBlueBlue.Controllers
{
    [Authorize(Roles = "Teacher,Administrators")]
    public class TopicController:Controller
    {
        private readonly TopicManager topicManager;

        public TopicController(TopicManager topicManager){
            this.topicManager = topicManager;
        }
        public async Task<IActionResult> Index()
        {
            List<TopicModel> topics =  await topicManager.FindTopicAllAsync();
            return View(topics);
        }
        [HttpGet]
        public IActionResult SelectCreate()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SelectCreate(string Select)
        {
            switch (Select)
            {
                case "Choice": return View("CreateChoice");
                case "Fill":return View("CreateFill");
                case "Judge":return View("CreateJudge");
                default:return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TopicModel topic)
        {
            if(ModelState.IsValid){
                var newModel=await topicManager.AddTopicAsync(topic);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var topic = topicManager.FindTopicById(id);
            return View(topic);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var topic = topicManager.FindTopicById(id);
            topicManager.DeleteTopic(topic);
            return  RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Search(string queryString)
        {
            var queryTopic = topicManager.FindTopicName(queryString);
            return View("Index",queryTopic);
        }

    }
}

Views/Topic/CreateChoice.cshtml
@{
    ViewData["Title"] = "添加选择题";
}
@model TopicModel
<form id="theForm" method="post" asp-action="Create">


    <div class="from-group row">
        <label asp-for="title" class="col-sm-2"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="title"/>
        </div>
    </div>


    <div class="from-group row">
        <label  class="col-sm-2">内容</label>
        <div class="col-sm-10">
            <input id="content" class="form-control" type="text"/>
        </div>
    </div>


    <div class="from-group row">
        <label asp-for="scores" class="col-sm-2"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="scores"/>
        </div>
    </div>


    <div class="from-group row">
        <label class="col-sm-2">A选项</label>
        <div class="col-sm-10">
            <input id="optionA" class="form-control" type="text"/>
        </div>
    </div>



    <div class="from-group row">
        <label class="col-sm-2">B选项</label>
        <div class="col-sm-10">
            <input id="optionB" class="form-control" type="text"/>
        </div>
    </div>



    <div class="from-group row">
        <label class="col-sm-2">C选项</label>
        <div class="col-sm-10">
            <input id="optionC" class="form-control" type="text"/>
        </div>
    </div>


    <div class="from-group row">
        <label class="col-sm-2">D选项</label>
        <div class="col-sm-10">
            <input id="optionD" class="form-control" type="text"/>
        </div>
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="inputGroupSelect">Options</label>
        </div>
        <select asp-for="answe" class="custom-select" id="inputGroupSelect">
            <option selected>请选择答案</option>
            <option value="A">A</option>
            <option value="B">B</option>
            <option value="C">C</option>
            <option value="D">D</option>
        </select>
    </div>
    <hr>
    <input type="hidden" asp-for="type" value="Choice"/>
    <input type="hidden" id="subcontent" asp-for="content"/>
    <div class="invalid" asp-validation-summary="ModelOnly"></div>
    <!-- <button type="submit" class="btn btn-primary btn-block">提交</button> -->
    <input type="button" class="btn btn-primary btn-block" onclick="Subimt()" value="提交"/>
</form>
<script>
    function Subimt(){
        var A = document.getElementById("optionA");
        var B = document.getElementById("optionB");
        var C = document.getElementById("optionC");
        var D = document.getElementById("optionD");
        var content = document.getElementById("content");
        var obj = {
            content:content.value,
            optionA:A.value,
            optionB:B.value,
            optionC:C.value,
            optionD:D.value
        }
        var subContent = document.getElementById("subcontent");
        subContent.value = JSON.stringify(obj);
        document.getElementById("theForm").submit();
    }
</script>

Views/Topic/CreateFill.cshtml
@{
    ViewData["Title"] = "添加填空题";
}
@model TopicModel
<form id="theForm" method="post" asp-action="Create">


    <div class="from-group row">
        <label asp-for="title" class="col-sm-2"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="title"/>
        </div>
    </div>


    <div class="from-group row">
        <label asp-for="content" class="col-sm-2"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="content"/>
        </div>
    </div>


    <div class="from-group row">
        <label asp-for="scores" class="col-sm-2"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="scores"/>
        </div>
    </div>

    <div class="from-group row">
        <label asp-for="answe" class="col-sm-2"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="answe"/>
        </div>
    </div>

    <hr>
    <input type="hidden" asp-for="type" value="Fill"/>
    <div class="invalid" asp-validation-summary="ModelOnly"></div>
    <button type="submit" class="btn btn-primary btn-block">提交</button>
</form>

Views/Topic/CreateJudge.cshtml
@{
    ViewData["Title"] = "添加判断题";
}
@model TopicModel
<form id="theForm" method="post" asp-action="Create">


    <div class="from-group row">
        <label asp-for="title" class="col-sm-2"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="title"/>
        </div>
    </div>


    <div class="from-group row">
        <label asp-for="content" class="col-sm-2"></label>
        <div class="col-sm-10">
            <input class="form-control" asp-for="content"/>
        </div>
    </div>


    <div class="from-group row">
        <label asp-for="scores" class="col-sm-2"></label>
        <div class="col-sm-10">
            <input class="form-control"  asp-for="scores"/>
        </div>
    </div>


    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="inputGroupSelect">Options</label>
        </div>
        <select asp-for="answe" class="custom-select" id="inputGroupSelect">
            <option selected>请选择答案</option>
            <option value="true">true</option>
            <option value="false">false</option>
        </select>
    </div>
    <hr>
    <input type="hidden" asp-for="type" value="Judge"/>
    <div class="invalid" asp-validation-summary="ModelOnly"></div>
    <button type="submit" class="btn btn-primary btn-block">提交</button>
    <!-- <input type="button" class="btn btn-primary btn-block" onclick="Subimt()" value="提交"/> -->
</form>

Views/Topic/Detail.cshtml
@model TopicModel
@{
    ViewData["Title"] = "查看题目";
}
<div class="list-group">
  <a class="list-group-item active">
   题目信息
  </a>
  <a class="list-group-item">题目：@Model.title</a>
  <a class="list-group-item">类型：@Model.type</a>
  <a class="list-group-item">分值：@Model.scores</a>
  <a class="list-group-item">内容：@Model.content</a>
  <a class="list-group-item">答案：@Model.answe</a>
</div>
<a asp-action="Index" class="btn btn-primary btn-lg active btn-block" role="button" aria-pressed="true">返回</a>

Views/Topic/Index.cshtml
@model List<TopicModel>
@{
    ViewData["Title"] = "题库";
}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">题目</th>
            <th scope="col"style="padding:0">
                <form class="form-inline my-2 my-lg-0" asp-action="Search" asp-controller="Topic" method="post" style="margin:0;">
                    <input name="queryString" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                </form>
            </th>
            <th scope="col" >
                
            </th>
            <th scope="col" >
                
            </th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
            <tr>
                <td>@item.id</td>
                <td>@item.title</td>
                <td><a asp-action="Detail" asp-route-id="@item.id">详细</a></td>
                <td>
                    <form id="subform @item.id" asp-action="Delete" asp-route-id="@item.id" method="post">
                        <a style="color:red;cursor:pointer" onclick="confirm('确认删除?')?document.getElementById('subform @item.id').submit():'';">删除</a>
                    </form>
                </td>
            </tr>
        </tbody>
    }
</table>

<a asp-action="SelectCreate" class="btn btn-primary btn-lg active btn-block" role="button" aria-pressed="true">添加题目</a>

Views/Topic/SelectCreate.cshtml
@{
    ViewData["Title"] = "选择添加题型";
}
@model TopicModel
<form asp-action="SelectCreate" asp-controller="Topic" method="post">
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="inputGroupSelect">Options</label>
        </div>
        <select name="Select" class="custom-select" id="inputGroupSelect">
            <option selected>请选择题目类型</option>
            <option value="Choice">选择题</option>
            <option value="Fill">填空题</option>
            <option value="Judge">判断题</option>
        </select>
    </div>
    
    <button class="btn btn-primary btn-lg active btn-block" role="button">选择</button>
</form>