Controllers/PaperController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SkyBlueBlue.Models;
using SkyBlueBlue.Services;

namespace SkyBlueBlue.Controllers
{
    [Authorize(Roles = "Teacher,Administrators")]
    public class PaperController : Controller
    {
        private readonly PaperManager paperManager;
        private readonly TopicManager topicManager;

        public PaperController(PaperManager paperManager, TopicManager topicManager)
        {
            this.paperManager = paperManager;
            this.topicManager = topicManager;
        }
        public async Task<IActionResult> Index()
        {
            List<PaperModel> papers = await paperManager.FindPaperAllAsync();
            return View(papers);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            List<TopicModel> topics = await topicManager.FindTopicAllAsync();
            ViewBag.Topics = topics;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PaperModel paper)
        {
            //添加创建人
            paper.teacherUserName=HttpContext.User.Identity.Name;
            var topicIdList = JsonConvert.DeserializeObject<List<TopicId>>(paper.body);
            int sum =0;
            //计算总分
            foreach (var item in topicIdList)
            {
                sum += topicManager.FindTopicById(item.id).scores;
            }
            paper.subtotal=sum;
            await paperManager.AddPaperAsync(paper);
            List<PaperModel> papers = await paperManager.FindPaperAllAsync();
            return View("Index", papers);
        }
        public IActionResult Detail(int id)
        {

            var paper = paperManager.FindPaperById(id);
            var topicIdList = JsonConvert.DeserializeObject<List<TopicId>>(paper.body);
            var topicIdTitleList = new List<TopicIdTitle>();
            foreach (var item in topicIdList)
            {
                var theTopic = topicManager.FindTitleById(item.id);
                if(theTopic==null)
                {
                    paperManager.CheckBodyById(id);
                    return RedirectToAction("Detail",id);
                }
                topicIdTitleList.Add(
                    new TopicIdTitle{
                        id=item.id,
                        title= theTopic
                    }
                ); 
                
            }
            ViewBag.Paper=paper;
            ViewBag.TopicIdList =topicIdTitleList;
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var paper = paperManager.FindPaperById(id);
            paperManager.DeletePaper(paper);
            return RedirectToAction(nameof(Index));
        }
        // public async Task<JsonResult> TopicData()
        // {
        //     List<TopicModel> topics =  await topicManager.FindTopicAll();
        //     return Json(topics);
        // }

    }
    public class TopicId
    {
        public int id { get; set; }
    }
    public class TopicIdTitle
    {
        public int id { get; set; }
        public string title { get; set; }
    }
}

Views/Paper/Create.cshtml
@{
    ViewData["Title"] = "创建试卷";
}
<!-- @using SkyBlueBlue.Models
@using System.Collections.Generic; -->
@model PaperModel
<link rel="stylesheet" href="/css/paperCreate.css" />
<link rel="stylesheet" type="text/css" href="/css/Transfer.css">
<form asp-action="Create" asp-controller="Paper" method="post" id="theForm">
    
    <ul class="list-group">
        <li class="list-group-item active">
            请填写试卷信息
        </li>
        <li class="list-group-item">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">标题</span>
                </div>
                <input asp-for="title">
            </div>
        </li>
        
    </ul>
    <div>
        <div class="ty-transfer mt20 ml20" id="ued-transfer-1">
            <div class="fl ty-transfer-list transfer-list-left">
                <div class="ty-transfer-list-head">
                    未选题目
                </div>
                <div class="ty-transfer-list-body">
                    <ul class="ty-tree-select">
                        @foreach (var item in ViewBag.Topics)
                        {  
                        <li id="@item.id">
                            <input type="hidden" id="@item.title">
                            <div class="ty-tree-div">
                                <label class="tyue-checkbox-wrapper">
                                    <span class="tyue-checkbox">
                                        <input type="checkbox" class="tyue-checkbox-input" id="tyue-checkbox-blue">
                                        <span class="tyue-checkbox-circle">
                                        </span>
                                    </span>
                                    <span class="tyue-checkbox-txt" title="@item.id">
                                        
                                        <a asp-controller="Topic" asp-action="Detail" asp-route-id="@item.id">@item.title</a>
                                    </span>
                                </label>
                            </div>
                        </li>
                        }
                    </ul>
                </div>
            </div>
            <div class="fl ty-transfer-operation">
                <span class="ty-transfer-btn-toright to-switch">
                </span>
                <span class="ty-transfer-btn-toleft to-switch">
                </span>
            </div>
            <div class="fl ty-transfer-list transfer-list-right">
                <div class="ty-transfer-list-head">
                    选中题目
                </div>
                <div class="ty-transfer-list-body">
                    <ul class="ty-tree-select" id="result">
                    </ul>
                </div>
            </div>
            <div class="clearboth">
            </div>
        </div>
    </div>
    <input id="thebody" type="hidden" asp-for="body">
    <br>

    <input type="button" class="btn btn-primary btn-lg active btn-block" onclick="Submit()" value="添加"/>
</form>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="/js/Transfer.js"></script>
<script type="text/javascript">
	$("#ued-transfer-1").transferItem();
</script>
<script>
    function Submit() {
        let keys =[];
        $("#result").find('li').each(function() {
            var obj = {'id':$(this).attr("id")};
            keys.push(obj);
        });
        $('#thebody').val(JSON.stringify(keys));
        $('#theForm').submit();
    }
</script>

Views/Paper/Detail.cshtml
@{
    ViewData["Title"] = "查看试卷";
}
<div class="list-group">
  <a class="list-group-item active">
   试卷信息
  </a>
  <a class="list-group-item">标题：@ViewBag.Paper.title</a>
  <a href="#" class="list-group-item">命题人：@ViewBag.Paper.teacherUserName</a>
  <a class="list-group-item">试卷总分值: @ViewBag.Paper.subtotal</a>
  <a class="list-group-item">试卷题目</a>
  @foreach (var item in ViewBag.TopicIdList)
  {
    <a class="list-group-item" asp-controller="Topic" asp-action="Detail" asp-route-id="@item.id">@item.id . @item.title</a>
  }
</div>
<a asp-action="Index" class="btn btn-primary btn-lg active btn-block" role="button" aria-pressed="true">返回</a>

Views/Paper/Index.cshtml
@model List<PaperModel>
@{
    ViewData["Title"] = "题库";
}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">试卷</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
            <tr>
                <td>@item.id</td>
                <td>@item.title</td>
                <td><a asp-action="Detail" asp-route-id="@item.id">详细</a></td>
                <td>
                    <form id="subform @item.id" asp-action="Delete" asp-route-id="@item.id" method="post">
                        <a style="color:red;cursor:pointer" onclick="confirm('确认删除?')?document.getElementById('subform @item.id').submit():'';">删除</a>
                    </form>
                </td>
            </tr>
        </tbody>
    }
</table>

<a asp-action="Create" class="btn btn-primary btn-lg active btn-block" role="button" aria-pressed="true">创建试卷</a>